environment_variables: {}
external_package_dirs:
- ../shared_code/
model_name: Reuse Demo truss
python_version: py39
requirements: []
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages: []
